server:
  port: 8083

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ps_transaction
    username: postgres
    password: nguyenkhang
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: transactionGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: transactionLogMessage:com.payment.system.common.dto.TransactionLogMessage

eureka:
  client:
    enabled: false


